hello-kubernetes:
  replicaCount: 1

  env:
    VAULT_SKIP: true

  hpa:
    enabled: true
    maxReplicas: 2

  ingress:
    enabled: true
    ingressClassName: kong
    annotations:
      argocd.argoproj.io/ignore-default-links: "true"
      link.argocd.argoproj.io/external-link: "http://hello-kubernetes.internal:30000"
    host: hello-kubernetes.internal
