hello-kubernetes:
  deployment:
    enabled: false

  rollouts:
    enabled: true
    strategy: canary
    blueGreen:
      autoPromotionEnabled: true

    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 10s }
        - setWeight: 40
        - pause: { duration: 10s }
        - setWeight: 60
        - pause: { duration: 10s }
        - setWeight: 80
        - pause: { duration: 10s }
      
    connectivityTest:
      enabled: false
      url: "http://hello-kubernetes-preview.internal:30000" 

  env:
    VAULT_SKIP: true

  hpa:
    enabled: true
    maxReplicas: 2

  httpRoute:
    enabled: true
    parentRefs:
      - name: kong
        namespace: kong
    hostnames:
      - hello-kubernetes.internal
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

  ingress:
    enabled: false
    ingressClassName: kong
    annotations:
      argocd.argoproj.io/ignore-default-links: "true"
      link.argocd.argoproj.io/external-link: "http://hello-kubernetes.internal:30000"
    host: hello-kubernetes.internal
