hello-kubernetes:
  replicaCount: 1

  env:
    VAULT_SKIP: true

  hpa:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: kong
    annotations: {}
    host: hello-kubernetes.internal
