---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-k8s-app-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          # The GitHub organization or user.
          owner: Constantin07
          # The Github repository
          repo: simple-k8s-app
          # (optional) use a GitHub App to access the API instead of a PAT.
          # appSecretName: repo-creds-gh
          # no tokenRef
          labels:
            - preview
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'simple-k8s-app-{{`{{branch_slug}}`}}-{{`{{number}}`}}'
      labels:
        environment: "dev"
        type: "pr-generated"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: simple-k8s-project
      source:
        repoURL: 'https://github.com/Constantin07/simple-k8s-app.git'
        targetRevision: '{{`{{head_short_sha}}`}}'
        path: pipelines/kubernetes/hello-kubernetes/deploy/hello-kubernetes
        # helm:
        #  valueFiles:
        #    - values-preview.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: simple-k8s
      syncPolicy:
         syncOptions:
           - CreateNamespace=true
         automated:
          prune: true
          selfHeal: true
